env:
  global:
    - CC_TEST_REPORTER_ID=c950f2561376ab0cbfaa7e9c5bfe495ee198077494af442c189d543bd89916e1
language: node_js
node_js:
  - "stable"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run test:cover
